version: "3.7"

services:
  query:
    build: .
    command: query-service
    depends_on:
      - postgres
      - nats
    ports:
      - 8080
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "admin"
      NATS_ADDRESS: nats:4222
  pusher:
    build: .
    command: pusher-service
    depends_on:
      - postgres
      - nats
    ports:
      - 8080
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "admin"
      NATS_ADDRESS: nats:4222
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "admin"
  nats:
    image: nats-streaming:0.9.2
    restart: always
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - query
      - pusher