DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS item;

DROP PROCEDURE IF EXISTS set_delivery;
DROP PROCEDURE IF EXISTS set_payment;
DROP PROCEDURE IF EXISTS set_item;
DROP PROCEDURE IF EXISTS set_order;
DROP PROCEDURE IF EXISTS set_order_item;
